# Generated by Django 4.0.4 on 2022-05-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
